### ISSUE TITLE
Sorting by Duration Field in Attendance Model

### ISSUE THREAD

**Issue by aswinshenoy** [amfoss/cms#2]
**Is your feature request related to a problem? Please describe.**
The list of entries in the attendance model are not sortable by duration, neither are they filterable

**Describe the solution you'd like**
The duration field in the attendance model needs to be sortable like others.

**Describe alternatives you've considered**
Presently there is no way in the admin to sort attendance entries by duration.

**Additional context**
Currently, the list looks like this and doesn't have a sort filter for duration field in attendance model
![image](https://user-images.githubusercontent.com/21276922/51859448-24552000-235d-11e9-84f6-fa57bd772e6d.png)

**Comment by aswinshenoy** [comment]
This issue arises because duration field is a calculated field from `session_start` and `session_end` and not actually a model field.

**Comment by abhishekbvs** [comment]
What all filters are needed for the duration field? Can u give the constraints according to the requirement?
