### ISSUE TITLE
Create College App & StudentProfile Model, Migrate fields from Profile field

### ISSUE THREAD

**Issue by aswinshenoy** [amfoss/cms#40]
Migrate college-level details like roll no, admission year, branch etc. to a new model `StudentProfile` under a new `College` App. 

**StudentProfileModel**
- User: One To One to User Model
- Roll Number: String
- Branch: ENUM / String
- Division: Char
- Admission Year: YEAR

*Please dont remove existing fields and add new fields in the same PR, as we wouldn't be able to merge it. As in that case, it will be difficult for us to migrate existing data in production. We will phase out the old fields as unused moving the associated functionalities to the new fields, and later on remove them though another PR.*

**Comment by Blackcipher101** [comment]
I would like to work on this issue

**Comment by aswinshenoy** [comment]
Hey there @Blackcipher101,
Sorry for responding late, as I was having my exams. This issue has been now fixed, with the college app being implemented into the CMS. Thank you for showing interest, hopefully you will find more interesting issues to solve in the future. 
We would love to see your contributions, thanks again.
