### ISSUE TITLE
Option to disable status update Thread for specific batch 

### ISSUE THREAD

**Issue by vibhoothi** [amfoss/cms#44]
Hi,

Currently thes status update thread is served to either whole batch or none which is good but it creates issue at multiple occasions since there is no option to disable to specific batch during exams or events or some other reasons.
It would be nice if we have an option in the admin panel of the status update thread where the admins can disable serving the status update to specific batch like 2019,2018 from thread for specific amount of time.

Best,
Vibhoothi

**Comment by aswinshenoy** [comment]
This feature has been now implemented. One can separately have member groups for each of those batch but sharing same status update thread etc., and then disable/enable as per choice.
![image](https://user-images.githubusercontent.com/21276922/68764540-e94c8080-0640-11ea-9f03-4468b61910d4.png)
